export const demoTransactions: Transaction[] = [
  {
    id: "demo-transfer-pending",
    $id: "demo-transfer-pending",
    name: "NovaPay transfer",
    paymentChannel: "online",
    type: "debit",
    accountId: "demo-checking",
    amount: 10,
    pending: true,
    category: "Transfer",
    date: "2026-06-01",
    image: "",
    $createdAt: "2026-06-01",
    channel: "online",
    senderBankId: "",
    receiverBankId: "",
  },
  {
    id: "demo-spotify",
    $id: "demo-spotify",
    name: "Spotify subscription",
    paymentChannel: "online",
    type: "debit",
    accountId: "demo-checking",
    amount: 12.99,
    pending: false,
    category: "Subscriptions",
    date: "2026-05-31",
    image: "",
    $createdAt: "2026-05-31",
    channel: "online",
    senderBankId: "",
    receiverBankId: "",
  },
  {
    id: "demo-market",
    $id: "demo-market",
    name: "Whole Foods Market",
    paymentChannel: "in store",
    type: "debit",
    accountId: "demo-checking",
    amount: 47.35,
    pending: false,
    category: "Food and Drink",
    date: "2026-05-30",
    image: "",
    $createdAt: "2026-05-30",
    channel: "in store",
    senderBankId: "",
    receiverBankId: "",
  },
  {
    id: "demo-savings",
    $id: "demo-savings",
    name: "Savings vault deposit",
    paymentChannel: "online",
    type: "credit",
    accountId: "demo-checking",
    amount: 50,
    pending: false,
    category: "Savings",
    date: "2026-05-29",
    image: "",
    $createdAt: "2026-05-29",
    channel: "online",
    senderBankId: "",
    receiverBankId: "",
  },
  {
    id: "demo-uber",
    $id: "demo-uber",
    name: "Uber ride",
    paymentChannel: "online",
    type: "debit",
    accountId: "demo-checking",
    amount: 18.2,
    pending: false,
    category: "Travel",
    date: "2026-05-28",
    image: "",
    $createdAt: "2026-05-28",
    channel: "online",
    senderBankId: "",
    receiverBankId: "",
  },
  {
    id: "demo-electric",
    $id: "demo-electric",
    name: "Electric bill",
    paymentChannel: "online",
    type: "debit",
    accountId: "demo-checking",
    amount: 74.1,
    pending: false,
    category: "Utilities",
    date: "2026-05-27",
    image: "",
    $createdAt: "2026-05-27",
    channel: "online",
    senderBankId: "",
    receiverBankId: "",
  },
  {
    id: "demo-card-payment",
    $id: "demo-card-payment",
    name: "Credit card payment",
    paymentChannel: "other",
    type: "credit",
    accountId: "demo-checking",
    amount: 125,
    pending: false,
    category: "Payment",
    date: "2026-05-26",
    image: "",
    $createdAt: "2026-05-26",
    channel: "other",
    senderBankId: "",
    receiverBankId: "",
  },
  {
    id: "demo-coffee",
    $id: "demo-coffee",
    name: "Coffee shop",
    paymentChannel: "in store",
    type: "debit",
    accountId: "demo-checking",
    amount: 6.45,
    pending: false,
    category: "Food and Drink",
    date: "2026-05-25",
    image: "",
    $createdAt: "2026-05-25",
    channel: "in store",
    senderBankId: "",
    receiverBankId: "",
  },
  {
    id: "demo-netflix",
    $id: "demo-netflix",
    name: "Netflix monthly plan",
    paymentChannel: "online",
    type: "debit",
    accountId: "demo-checking",
    amount: 15.49,
    pending: false,
    category: "Subscriptions",
    date: "2026-05-24",
    image: "",
    $createdAt: "2026-05-24",
    channel: "online",
    senderBankId: "",
    receiverBankId: "",
  },
  {
    id: "demo-train",
    $id: "demo-train",
    name: "Metro card reload",
    paymentChannel: "online",
    type: "debit",
    accountId: "demo-checking",
    amount: 22,
    pending: false,
    category: "Travel",
    date: "2026-05-23",
    image: "",
    $createdAt: "2026-05-23",
    channel: "online",
    senderBankId: "",
    receiverBankId: "",
  },
  {
    id: "demo-phone",
    $id: "demo-phone",
    name: "Mobile plan",
    paymentChannel: "online",
    type: "debit",
    accountId: "demo-checking",
    amount: 39.99,
    pending: false,
    category: "Utilities",
    date: "2026-05-22",
    image: "",
    $createdAt: "2026-05-22",
    channel: "online",
    senderBankId: "",
    receiverBankId: "",
  },
  {
    id: "demo-vault-reward",
    $id: "demo-vault-reward",
    name: "Vault reward",
    paymentChannel: "online",
    type: "credit",
    accountId: "demo-checking",
    amount: 8.75,
    pending: false,
    category: "Savings",
    date: "2026-05-21",
    image: "",
    $createdAt: "2026-05-21",
    channel: "online",
    senderBankId: "",
    receiverBankId: "",
  },
];

export const withDemoTransactions = (
  transactions: Transaction[] = [],
): Transaction[] => {
  if (transactions.length >= 11) return transactions;

  const existingIds = new Set(transactions.map((transaction) => transaction.id));
  const missingTransactions = demoTransactions.filter(
    (transaction) => !existingIds.has(transaction.id),
  );

  return [...transactions, ...missingTransactions];
};
